#配置服务器的端口号
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  mail:
    #发送人邮件地址
      username: 990355623@qq.com
      #邮箱授权码
      password: ydldzdwlkqribfbh
      #什么邮箱
      host: smtp.qq.com
      properties:
        mail:
          smtp:
            ssl:
              enable: true
    #配置mybatis
  redis:
    host: 192.168.5.149
  data:
    mongodb:
      uri: mongodb://BBS:BBSpwd@192.168.5.149:27017/BBS

mybatis:
    type-aliases-package: com.bbs.demo.pojo #扫描实体类所在的包路径
    mapper-locations: mapper/*Mapper.xml #扫描所有的映射文件
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


